{
	"version": 1737702732,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/redgreenlight-sheet0.png",
		"images/dollhead-sheet0.png",
		"images/dollhead-sheet1.png",
		"images/particles.png",
		"images/oceanlayer-sheet0.png",
		"images/ship-sheet0.png",
		"images/image_fx_4photoroom-sheet0.png",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/redlightgreenlighthowto-sheet2.png",
		"images/play-sheet0.png",
		"media/voice 2.m4a",
		"media/voice 2.ogg",
		"media/voice 3.m4a",
		"media/voice 3.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"media/voice 0.m4a",
		"media/voice 0.ogg",
		"media/bubble 1.m4a",
		"media/bubble 1.ogg",
		"media/bubble 2.m4a",
		"media/bubble 2.ogg",
		"media/voice 5.m4a",
		"media/voice 5.ogg",
		"media/voice 1.m4a",
		"media/voice 1.ogg",
		"media/voice 4.m4a",
		"media/voice 4.ogg",
		"media/voice 6.m4a",
		"media/voice 6.ogg",
		"media/dead meme's chest - bgm.m4a",
		"media/dead meme's chest - bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}